scriptencoding utf-8

" ----------------------------------------------------------------------------
" display tweaks
" ----------------------------------------------------------------------------
"{{{

" window
set lines=999 columns=180
set fuopt+=maxhorz,maxvert

" font
set guifont=Hasklig:h14
set macligatures
set macthinstrokes

" remove toolbar
set guioptions-=T

" remove scrollbars
set guioptions-=L
set guioptions-=r

" remove menu
set guioptions-=m

" Change cursor style when entering INSERT mode
let s:tmux = exists('$TMUX')

let g:end_insert   = "\<Esc>]50;CursorShape=1\x7"
let g:start_insert = "\<Esc>]50;CursorShape=0\x7"

if s:tmux
  let g:start_insert = s:TmuxWrap(start_insert)
  let g:end_insert   = s:TmuxWrap(end_insert)
endif

let &t_SI = g:start_insert
let &t_EI = g:end_insert

"}}}

" ----------------------------------------------------------------------------
" theme
" ----------------------------------------------------------------------------
"{{{

set background=dark
colorscheme hybrid

"}}}
"
" ----------------------------------------------------------------------------
" Local overrides
" ----------------------------------------------------------------------------
"{{{

if filereadable(glob('~/.gvimrc.local'))
  source ~/.gvimrc.local
endif

"}}}
