"appearance {{{

set lines=60 columns=150
set guifont=Source\ Code\ Pro\ for\ Powerline:h13
"set guifont=Consolas\ for\ Powerline:h14

" remove toolbar
set go-=T

" remove scrollbars
set go-=L
set go-=r

"}}}

"theme {{{

syntax on
"set background=light
set background=dark

"colorscheme solarized
colorscheme seoul256

"set transparency=2

"}}}
