" ----------------------------------------------------------------------------
" pathogen
" ----------------------------------------------------------------------------
"{{{

filetype off
call pathogen#infect()
call pathogen#helptags()
filetype plugin indent on

"}}}

" ----------------------------------------------------------------------------
" modularised settings
" ----------------------------------------------------------------------------
"{{{

set nocompatible

source ~/.vim/config.vim
source ~/.vim/filetypes.vim
source ~/.vim/keys.vim
source ~/.vim/plugins.vim

"}}}

" ----------------------------------------------------------------------------
" local overrides
" ----------------------------------------------------------------------------
"{{{

if filereadable(glob("~/.vimrc.local"))
  source ~/.vimrc.local
endif

"}}}
