" ----------------------------------------------------------------------------
" pathogen
" ----------------------------------------------------------------------------
"{{{

let g:pathogen_disabled = ['tern_for_vim']
call pathogen#infect()
syntax on
filetype plugin indent on

"}}}

" ----------------------------------------------------------------------------
" modularised settings
" ----------------------------------------------------------------------------
"{{{

source ~/.vim/config.vim
source ~/.vim/filetypes.vim
source ~/.vim/keys.vim
source ~/.vim/plugins.vim

"}}}

" ----------------------------------------------------------------------------
" local overrides
" ----------------------------------------------------------------------------
"{{{

if filereadable(glob("~/.vimrc.local"))
  source ~/.vimrc.local
endif

"}}}
