# make sure local takes precendence
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
export MANPATH=/usr/local/opt/coreutils/libexec/gnuman:$MANPATH

# for gnu bin on osx
if [ -d /usr/local/opt/coreutils/libexec/gnubin ]; then
  export PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
fi

# for XQuartz
if [ -d /usr/X11 ]; then
  export PATH=/usr/X11/bin:$PATH
fi

# texlive
if [ -d /usr/local/texlive/2016/bin/x86_64-darwin ]; then
  export PATH=/usr/local/texlive/2016/bin/x86_64-darwin:$PATH
fi

# for nvm
if [ -d ~/.nvm ] && [ -d /usr/local/opt/nvm ]; then
  export NVM_DIR=~/.nvm
  source /usr/local/opt/nvm/nvm.sh
fi

# for perlbrew
if [ -d ~/.perl5/perlbrew ]; then
  source $HOME/.perl5/perlbrew/etc/bashrc
  #export PATH=$HOME/.perl5/perlbrew/bin:$PATH
  export PERLBREW_ROOT=$HOME/.perl5/perlbrew
fi

# for homebrew python
if [ -d /usr/local/opt/python ]; then
  export PATH="/usr/local/opt/python/libexec/bin:$PATH"
fi

# for groovy
if [ -d /usr/local/opt/groovy ]; then
   export GROOVY_HOME=/usr/local/opt/groovy/libexec
fi

# editor and utils
export EDITOR=vim
export PAGER=less
export COPYFILE_DISABLE=1

# disable oh-my-zsh updates
export DISABLE_AUTO_UPDATE=true

# homebrew stuff
export HOMEBREW_NO_ANALYTICS=1

# fzf options
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_DEFAULT_OPTS="--inline-info"
#export FZF_CTRL_R_OPTS="-e"

# for thefuck
eval "$(thefuck --alias)"
