# make sure local takes precendence
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
export MANPATH=/usr/local/opt/coreutils/libexec/gnuman:$MANPATH

# for gnu bin on osx
if [ -d /usr/local/opt/coreutils/libexec/gnubin ]; then
  export PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
fi

# for XQuartz
if [ -d /usr/X11 ]; then
  export PATH=/usr/X11/bin:$PATH
fi

# texlive
if [ -d /usr/local/texlive/2018/bin/x86_64-darwin ]; then
  export PATH=/usr/local/texlive/2018/bin/x86_64-darwin:$PATH
fi

# for nvm
if [ -d ~/.nvm ] && [ -d /usr/local/opt/nvm ]; then
  export NVM_DIR=~/.nvm
  source /usr/local/opt/nvm/nvm.sh
fi

# for php (homebrew)
if [ -d /usr/local/opt/php@7.2 ]; then
    export PATH=/usr/local/opt/php@7.2/bin:$PATH
fi

# for postgresql (homebrew)
if [ -d /usr/local/opt/postgresql@10 ]; then
    export PATH=/usr/local/opt/postgresql@10/bin:$PATH
fi

# for perlbrew
if [ -d ~/.perl5/perlbrew ]; then
  source $HOME/.perl5/perlbrew/etc/bashrc
  #export PATH=$HOME/.perl5/perlbrew/bin:$PATH
  export PERLBREW_ROOT=$HOME/.perl5/perlbrew
fi

# for pyenv/python
if [ -d ~/.pyenv/shims ]; then
  export PATH="$HOME/.pyenv/shims:$PATH"
fi

# for groovy
if [ -d /usr/local/opt/groovy ]; then
  export GROOVY_HOME=/usr/local/opt/groovy/libexec
fi

# for rust/cargo
if [ -d ~/.cargo/bin ]; then
  export PATH="$HOME/.cargo/bin:$PATH"
fi

# for composer vendor bins
if [ -d ~/.composer/vendor/bin ]; then
  export PATH=$HOME/.composer/vendor/bin:$PATH
fi

# for VS Code
if [ -d "/Applications/Visual Studio Code.app/Contents/Resources/app/bin" ]; then
  export PATH="/Applications/Visual Studio Code.app/Contents/Resources/app/bin:$PATH"
fi

# Base16 Shell
if [ -d ~/.config/base16-shell ]; then
  BASE16_SHELL="$HOME/.config/base16-shell/"
  [ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
      eval "$("$BASE16_SHELL/profile_helper.sh")"
fi

# editor and utils
export EDITOR=vim
export PAGER=less
export COPYFILE_DISABLE=1

# disable oh-my-zsh updates
export DISABLE_AUTO_UPDATE=true

# homebrew stuff
export HOMEBREW_NO_ANALYTICS=1

# fzf options
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_DEFAULT_OPTS="--inline-info"
#export FZF_CTRL_R_OPTS="-e"
