# make sure local takes precendence
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
export MANPATH=/usr/local/opt/coreutils/libexec/gnuman:$MANPATH

# for gnu bin on osx
if [ -d /usr/local/opt/coreutils/libexec/gnubin ]; then
  export PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
fi

# for local Python
if [ -d /usr/local/lib/python2.7/site-packages ]; then
  export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH
fi

if [ -d /usr/local/Frameworks/Python.framework/Versions/2.7/bin ]; then
  export PATH=/usr/local/Frameworks/Python.framework/Versions/2.7/bin:$PATH
fi

# local java
if [ -d ~/.java/lib ]; then
  export CLASSPATH=~/.java/lib:$CLASSPATH
fi

# for XQuartz
if [ -d /usr/X11 ]; then
  export PATH=/usr/X11/bin:$PATH
fi

# for nvm
if [ -d ~/.nvm ] && [ -d /usr/local/opt/nvm ]; then
  export NVM_DIR=~/.nvm
  source /usr/local/opt/nvm/nvm.sh
fi

# for perlbrew
if [ -d ~/.perl5/perlbrew ]; then
  source $HOME/.perl5/perlbrew/etc/bashrc
  #export PATH=$HOME/.perl5/perlbrew/bin:$PATH
  export PERLBREW_ROOT=$HOME/.perl5/perlbrew
fi

# for phpbrew
if [ -d ~/.phpbrew ]; then
  source $HOME/.phpbrew/bashrc
fi

# for groovy
if [ -d /usr/local/opt/groovy/libexec ]; then
  export GROOVY_HOME=/usr/local/opt/groovy/libexec
fi

# texlive
if [ -d /usr/local/texlive/2015/bin/x86_64-darwin ]; then
  export PATH=/usr/local/texlive/2015/bin/x86_64-darwin:$PATH
fi

# for sqlite
if [ -d /usr/local/opt/sqlite ]; then
  export PATH=/usr/local/opt/sqlite/bin:$PATH
fi

# editor and utils
export EDITOR=vim
export PAGER=less
export COPYFILE_DISABLE=1

# disable oh-my-zsh updates
export DISABLE_AUTO_UPDATE=true

# homebrew stuff
export HOMEBREW_GITHUB_API_TOKEN=ea199008fc0ec8d298a04e26ac5da69d5528abad
export HOMEBREW_NO_ANALYTICS=1

# for thefuck
eval "$(thefuck --alias)"
