# export LANG
export LC_CTYPE=C
export LANG=C

# oh-my-zsh setup and config {{{

export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="$HOME/.zsh"
export ZSH_THEME="scott"
export DISABLE_AUTO_UPDATE="true"
plugins=(brew git fasd aliases zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

# }}}

# environment and path {{{

export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH

# for XQuartz
if [ -d /usr/X11 ]; then
  export PATH=/usr/X11/bin:$PATH
fi

# for mactex
if [ -d /usr/texlive ]; then
  export PATH=/usr/texlive/bin/x86_64-darwin:$PATH
fi

# for autojump (plugin doesn't seem to work)
if [ -f `/usr/local/bin/brew --prefix`/etc/autojump.zsh ]; then
  source `/usr/local/bin/brew --prefix`/etc/autojump.zsh
fi

# for nvm
if [ -d ~/.nvm ]; then
  export NVM_DIR=~/.nvm
  source $(brew --prefix nvm)/nvm.sh
fi

# for rbenv
#eval "$(rbenv init -)"

# for perlbrew
if [ -d ~/.perl5/perlbrew ]; then
  source $HOME/.perl5/perlbrew/etc/bashrc
  #export PATH=$HOME/.perl5/perlbrew/bin:$PATH
  export PERLBREW_ROOT=$HOME/.perl5/perlbrew
fi

# for phpbrew
if [ -d ~/.phpbrew ]; then
  source $HOME/.phpbrew/bashrc
fi

# make sure local takes precendence
export PATH=/usr/local/bin:/usr/local/sbin:$PATH

export EDITOR=vim
export PAGER=less
export COPYFILE_DISABLE=1

# history
HISTFILE=$HOME/.zsh-history
HISTSIZE=1000
SAVEHIST=1000

#}}}

# key bindings {{{

# vi style incremental search
bindkey '^R' history-incremental-search-backward
bindkey '^S' history-incremental-search-forward
bindkey '^P' history-search-backward
bindkey '^N' history-search-forward
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

# command line movement
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line
bindkey "^W" backward-delete-word
bindkey "^b" backward-word
bindkey "^f" forward-word
bindkey "^d" delete-word
bindkey "^k" kill-line
#bindkey "${key[Delete]}" delete-char

#}}}

# Source local configuration {{{

if [ -f $HOME/.zshrc_local ];
  then source $HOME/.zshrc_local
fi

# }}}

# welcome message
echo -e "Kernel Information: " `uname -smr`
echo -e "`zsh --version`"
echo -ne "Uptime: "; uptime
echo -ne "Server time is: "; date
