#zmodload zsh/zprof

# environment (source here due to macvim issue) {{{

source $HOME/.zsh/zshenv

#}}}

# *gen setup and config {{{

ZGEN_RESET_ON_CHANGE=($HOME/.zshrc)
source $HOME/.zsh/plugins/zgen/zgen.zsh

if ! zgen saved; then
  # oh-my-zsh plugins
  zgen oh-my-zsh
  zgen oh-my-zsh plugins/git
  zgen oh-my-zsh plugins/fasd
  zgen oh-my-zsh plugins/brew
  zgen oh-my-zsh plugins/osx
  zgen oh-my-zsh plugins/asdf
  #zgen oh-my-zsh plugins/vi-mode

  # other plugins
  zgen load Tarrasch/zsh-bd
  zgen load hlissner/zsh-autopair

  # local plugins
  zgen load "${HOME}/.zsh/plugins/fzf"
  zgen load "${HOME}/.zsh/plugins/fzf-tab"
  zgen load "${HOME}/.zsh/plugins/zsh-autosuggestions"

  # zsh-users plugins
  zgen load zsh-users/zsh-completions src
  zgen load zsh-users/zsh-history-substring-search
  zgen load zsh-users/zsh-syntax-highlighting

  # theme
  zgen load romkatv/powerlevel10k powerlevel10k
  #zgen load "${HOME}/.zsh/themes/scott/scott.zsh-theme"

  zgen save
fi

# }}}

# modularised config {{{

for config_file (history coloured-man-pages keybindings aliases misc); do
  source $HOME/.zsh/config/$config_file.zsh
done

#}}}

# additional config {{{

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.p10k.zsh ] && source ~/.p10k.zsh
[ -f ~/.zshrc.local ] &&  source ~/.zshrc.local

#}}}

# welcome message {{{

if [[ "$(uname -o)" == 'Darwin' ]]; then
  echo -e "$fg[yellow]Distro:$reset_color OS X $fg[cyan]$(sw_vers -productVersion)$reset_color"
else
  echo -e "$fg[yellow]Distro:$reset_color $(uname -io)"
fi
echo -e "$fg[yellow]Kernel:$reset_color $(uname -smr)"
echo -e "$fg[yellow]Shell:$reset_color $(zsh --version)"
echo -e "$fg[yellow]Uptime:$reset_color $(uptime | sed 's/^.*up/up/' | sed -e 's/  */ /g')"
echo -ne "$fg[yellow]Current Time:$reset_color "; date

#}}}

#zprof

